######################################################################
# Automatically generated by qmake (2.01a) Sat May 18 21:14:53 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += opengl
# Input
HEADERS += hedgemesh.h mainwindow.h parser.h parserstruct.h viewer.h
SOURCES += hedgemesh.cpp main.cpp mainwindow.cpp parser.cpp viewer.cpp
