######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 30 11:35:21 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += opengl

# Input
HEADERS += mainwindow.h parser.h viewer.h
SOURCES += main.cpp mainwindow.cpp parser.cpp viewer.cpp
